# Generated by Django 6.0.7 on 2026-08-13 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='products/')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('in_stock', 'Còn hàng'), ('warning_stock', 'Sắp hết hàng'), ('out_of_stock', 'Hết hàng'), ('discontinued', 'Ngừng bán')], default='in_stock', max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('layout', models.CharField(choices=[('layout_65', 'Layout 65%'), ('layout_75', 'Layout 75%'), ('layout_100', 'Layout Fullsize')], max_length=15, verbose_name='Layout')),
                ('keyboard_type', models.CharField(choices=[('mech', 'Bàn phím cơ'), ('he', 'Bàn phím HE'), ('low_profile', 'Bàn phím Low Profile')], max_length=20, verbose_name='Loại bàn phím')),
                ('connection', models.CharField(choices=[('wired', 'có dây'), ('wireless', 'không dây')], max_length=15, verbose_name='Kiểu kết nối')),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Keycap',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('profile', models.CharField(choices=[('cherry', 'Cherry'), ('xda', 'XDA'), ('moa', 'MOA'), ('artisan', 'Artisan')], max_length=10, verbose_name='Profile')),
                ('material', models.CharField(choices=[('pbt', 'PBT'), ('abs', 'ABS')], max_length=5, verbose_name='Chất liệu')),
                ('print_tech', models.CharField(choices=[('double_shot', 'Doubleshot'), ('dye_sub', 'Dyesub')], max_length=15, verbose_name='Công nghệ in')),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='ModTool',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('mt_type', models.CharField(choices=[('tools', 'Dụng cụ mod'), ('lube', 'Mỡ lube'), ('modding', 'Vật liệu mod')], max_length=20, verbose_name='Thể loại')),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('connection', models.CharField(choices=[('wired', 'có dây'), ('wireless', 'không dây')], max_length=15, verbose_name='Kiểu kết nối')),
                ('brand', models.CharField(choices=[('logitech', 'Logitech'), ('razer', 'Razer'), ('gravastar', 'Gravastar'), ('others', 'Khác')], max_length=15, verbose_name='Thương hiệu')),
                ('mouse_type', models.CharField(choices=[('office', 'Văn phòng'), ('gammingGamming', 'Gamming')], max_length=15, verbose_name='Thể loại')),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('switch_type', models.CharField(choices=[('linear', 'Linear'), ('tactile', 'Tactile'), ('slient', 'Slient'), ('he', 'HE')], max_length=15, verbose_name='Loại switch')),
            ],
            bases=('products.product',),
        ),
    ]
